-- INSERT INTO UNID_MEDIDA

INSERT INTO UNID_MEDIDA (NOME, ABREVIATURA) VALUES ('Milimetros', 'mm');
INSERT INTO UNID_MEDIDA (NOME, ABREVIATURA) VALUES ('Centímetros', 'cm');
INSERT INTO UNID_MEDIDA (NOME, ABREVIATURA) VALUES ('Metros', 'm');
INSERT INTO UNID_MEDIDA (NOME, ABREVIATURA) VALUES ('Miligramas', 'mg');
INSERT INTO UNID_MEDIDA (NOME, ABREVIATURA) VALUES ('Gramas', 'g');
INSERT INTO UNID_MEDIDA (NOME, ABREVIATURA) VALUES ('Quilogramas', 'kg');
INSERT INTO UNID_MEDIDA (NOME, ABREVIATURA) VALUES ('Mililitros', 'ml');
INSERT INTO UNID_MEDIDA (NOME, ABREVIATURA) VALUES ('Centilitros', 'cl');
INSERT INTO UNID_MEDIDA (NOME, ABREVIATURA) VALUES ('Litros', 'l');
INSERT INTO UNID_MEDIDA (NOME, ABREVIATURA) VALUES ('Unidades', 'un');



-- INSERT INTO CATEGORIA

INSERT INTO CATEGORIA (NOME) VALUES ('Biscuit');
INSERT INTO CATEGORIA (NOME) VALUES ('Bijuteria');
INSERT INTO CATEGORIA (NOME) VALUES ('Bordado');
INSERT INTO CATEGORIA (NOME) VALUES ('Carpintaria');
INSERT INTO CATEGORIA (NOME) VALUES ('Cerâmica');
INSERT INTO CATEGORIA (NOME) VALUES ('Cortiça');
INSERT INTO CATEGORIA (NOME) VALUES ('Crochê');
INSERT INTO CATEGORIA (NOME) VALUES ('EVA');
INSERT INTO CATEGORIA (NOME) VALUES ('Macramé');
INSERT INTO CATEGORIA (NOME) VALUES ('Renda');
INSERT INTO CATEGORIA (NOME) VALUES ('Patchwork');
INSERT INTO CATEGORIA (NOME) VALUES ('Pintura em tecido');
INSERT INTO CATEGORIA (NOME) VALUES ('Pintura em tela');
INSERT INTO CATEGORIA (NOME) VALUES ('Porcelana');
INSERT INTO CATEGORIA (NOME) VALUES ('Tapeçaria');
INSERT INTO CATEGORIA (NOME) VALUES ('Tecido');
INSERT INTO CATEGORIA (NOME) VALUES ('Tricô');
INSERT INTO CATEGORIA (NOME) VALUES ('Outra');